url: http://bryanhaggerty.com
name: "Blog of Bryan Haggerty, User experience designer"
permalink: /blog/:year/:month/:title/

baseurl: /blog

paginate: 5
paginate_path: "/blog/page/:num"

gems:
    - jekyll-paginate
    - jekyll-redirect-from