url: http://bryanhaggerty.com
name: "Blog of Bryan Haggerty, User experience designer"
permalink: /blog/:year/:month/:title/

baseurl: /blog

paginate: 5
paginate_path: "/blog/page/:num"

gems:
    - jekyll-paginate
    - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
    - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
